language: python
cache: pip
jobs:
  include:
    - name: "Python 3.7.0 on Bionic Linux"
      dist: bionic
      python: 3.7
    - name: "Python 3.8.0 on Bionic Linux"
      dist: bionic
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - stage: deploy
      python: 3.7
      script: skip

install:
  - ./.travis/linux_r_setup.sh
  - ./.travis/unix_r_install.sh
  - pip3 install -r requirements.txt
  - pip3 install .
  - pip3 install pytest-cov codecov
script:
  - pytest --cov-report=html --cov=madbayes --cov-append tests_python
  - NUMBA_DISABLE_JIT=0 pytest --cov-report=html --cov=madbayes --cov-append tests_numba
  - codecov
