name: wi
channels:
    - conda-forge
    - numba
dependencies:
    - python>=3.7
    - icc_rt
    - pydot
    - matplotlib
    - networkx>=2.4
    - numba>=0.48
    - numpy
    - scipy
    - pandas
    - xarray
    - tbb
    - lark-parser
