name: wi
channels:
    - conda-forge
    - numba
dependencies:
    - python>=3.7,<3.8
    - icc_rt
    - matplotlib
    - networkx>=2.4
    - numba>=0.48
    - numpy
    - pandas
    - xarray
    - tbb
    - lark-parser
